### ISSUE TITLE
Field Link doesn't create a fragment (ref) link - but the `#` does

### ISSUE THREAD

**Issue by dbvj** [buildresonance/resonance-webapp-docs#110]
**Describe the bug**
(See images) - clicking on a field link (#1 in image) does not create a fragment link, but clicking on the `#` (#2 in image) does.

`#1` output: https://docs.buildresonance.com/demand/api/graphql-admin/reference/objects/demand-hq-notification/#
`#2` output: https://docs.buildresonance.com/demand/api/graphql-admin/reference/objects/demand-hq-notification/#code-style-fontweight-normal-demandhqnotificationbsenderreferencekeybcodestring-

![Image](https://github.com/buildresonance/resonance-webapp-docs/assets/61169447/249cc428-b5ea-4221-a724-3b20fa68bc21)

**Comment by dbvj** [comment]
This seems like the primary anchor should create a fragment / ref link?

**Comment by dkershner6** [comment]
This is a docusaurus plugin we have no control over, maybe updating will help or something, but we ain't fixing.
